image: node:20

stages: [deploy]

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
    # SPA-fallback, чтобы прямые переходы не давали 404
    - cp public/index.html public/404.html
  artifacts:
    paths: [public]
  only: [master, homework]
